from models.stock import Stock
from models import storage
from models.area import Area
import os

stock1 = Stock(product='Beef_stew', value=150, description='A plate of beef stew', image='images/beef_stew.jpg', category='Foods')
stock2 = Stock(product='Biriani', value=250, description='A plate of biriani', image='images/biriani.jpg', category='Foods')
stock3 = Stock(product='Chapati', value=70, description='2 rolls of chapatis', image='images/chapati.jpg', category='Foods')
stock4 = Stock(product='Chicken', value=200, description='3 pieces of chicken', image='images/chicken.jpg', category='Foods')
stock5 = Stock(product='Coffee', value=50, description='A cup of coffee', image='images/cofee.jpg', category='Beverages')
stock6 = Stock(product='Chips', value=175, description='A plate of chips', image='images/chips.jpg', category='Foods')
stock7 = Stock(product='Fish', value=100, description='1 fried fish', image='images/fish.jpg', category='Foods')
stock8 = Stock(product='Githeri', value=75, description='A plate of githeri', image='images/githeri.jpg', category='Foods')
stock9 = Stock(product='Hamburger', value=100, description='One burger', image='images/hamburger.jpg', category='Foods')
stock10 = Stock(product='Lemon tea', value=50, description='A cup of lemon tea', image='images/lemon_tea.jpg', category='Beverages')
stock11 = Stock(product='Mango Juice', value=75, description='A glass of mango juice', image='images/mixed_juice.jpg', category='Drinks')
stock12 = Stock(product='Nyama Choma', value=200, description='A plate of nyama choma', image='images/nyama.jpg', category='Foods')
stock13 = Stock(product='Orange Juice', value=75, description='A glass of orange juice', image='images/orange_juice.jpg', category='Drinks')
stock14 = Stock(product='Pilau', value=200, description='A plate of pilau', image='images/pilau.jpg', category='Foods')
stock15 = Stock(product='Samosas', value=50, description='1 meat samosa', image='images/samosa.jpg', category='Foods')
stock16 = Stock(product='Sausages', value=60, description='2 sausages', image='images/sausage.jpg', category='Foods')
stock17 = Stock(product='Tea', value=50, description='A cup of tea', image='images/tea.jpg', category='Beverages')
stock18 = Stock(product='Ugali', value=40, description='A plate of plain ugali', image='images/ugali.jpg', category='Foods')
stock19 = Stock(product='Water', value=65, description='A bottle of water', image='images/water.jpg', category='Drinks')
area1 = Area(name='Nairobi')
area2 = Area(name='Mombasa')
area3 = Area(name='Kisumu')

storage.new(area1)
storage.new(area2)
storage.new(area3)
storage.new(stock1)
storage.new(stock2)
storage.new(stock3)
storage.new(stock4)
storage.new(stock5)
storage.new(stock6)
storage.new(stock7)
storage.new(stock8)
storage.new(stock9)
storage.new(stock10)
storage.new(stock11)
storage.new(stock12)
storage.new(stock13)
storage.new(stock14)
storage.new(stock15)
storage.new(stock16)
storage.new(stock17)
storage.new(stock18)
storage.new(stock19)
storage.save()

